### PR TITLE
Add exec office hours 28

### LINKED ISSUE #28: Office hours missing from exec page
The office need to be added for those execs who have them.

### PR DESCRIPTION
**Pull request by PeterGhimself**
This PR resolves #28 
## Summary
- made role names bold (+ some CS changes)
- added office hours
- merged both of @alienorlgrst 's `execBlocks` into one
- slightly decreased the top-bottom padding of all `execBlocks`

the new look:
screenshot from 2017-09-25 15-30-18

screenshot from 2017-09-25 15-30-58

### CODE REVIEW

**Comment by PeterGhimself** [comment]
@n0pan I agree, and I'm not sure why it was decided to put them all bunched up like that in the first place.
I _did_ take the liberty to make some fast minor style changes, but I don't want to make the purpose of this PR diverge too much from the main point: adding the office hours for executives.
You're more than welcome to open a new issue regarding this, and see who bites or assign it to yourself.

**Comment by n0pan** [comment]
@PeterGhimself Fair enough. Office hours look good.

**Comment by alienorlgrst** [comment]
Btw execs from 2016-2017 dont have office hours, only us this year do.

**Comment by PeterGhimself** [comment]
@alienorlgrst I removed the office hours from 2016-2017 tab

**Pull request merged**
